-- Crear una vez en oracle_dw (usuario APP). No ejecutar en cada corrida.
-- Runtime: Hop pl_form_informes (TRUNCATE + INSERT). Incluye FECHA_CARGA.
-- Preferible: python/stg/ensure_dw_tables.py (CREATE o ALTER ADD FECHA_CARGA).

CREATE TABLE APP.DW_INF_CONSOL_FORM (
  FUENTE VARCHAR2(500),
  ANIO NUMBER,
  MES_CORTE VARCHAR2(500),
  ARCHIVO VARCHAR2(1000),
  OBJETO_R VARCHAR2(1000),
  INFORME VARCHAR2(1000),
  FECHA_INFORME DATE,
  EXPEDIENTE VARCHAR2(1000),
  CUC_INAPS VARCHAR2(1000),
  ADMIN VARCHAR2(1000),
  UF VARCHAR2(1000),
  HECHO_VERIF CLOB,
  TIPIFICA_HECHO VARCHAR2(2000),
  CLASIF_HECHO VARCHAR2(500),
  RESULT_HECHO VARCHAR2(2000),
  MOTIVO_ARCHIV_CONOC VARCHAR2(2000),
  RECOM_INFORME VARCHAR2(2000),
  DOC_CIERRE VARCHAR2(2000),
  NRO_DOC_CIERRE VARCHAR2(1000),
  FECHA_DOC_CIERRE DATE,
  FECHA_DERIV DATE,
  FEINICIO DATE,
  FEFIN DATE,
  TIPOSUP_INAPS VARCHAR2(500),
  SUPERV_ORIENTATIVA VARCHAR2(500),
  MES_META VARCHAR2(500),
  TIPO_INF VARCHAR2(500),
  TXCOORDINACION VARCHAR2(1000),
  OBLIG_CUMPL NUMBER,
  OBL_INCUMPLIDA NUMBER,
  SUBSANA VARCHAR2(500),
  SUBS_LEVE NUMBER,
  SUBS_TRAS NUMBER,
  SUBSANADO NUMBER,
  CUMPLIM_ADD NUMBER,
  FILTRO_INF_UNIQ NUMBER,
  TIPOACCION_INAPS VARCHAR2(500),
  FECHA_REAL DATE,
  YEAR_APROB NUMBER,
  FEINI_ELAB_INF DATE,
  TX_DOCUMENTO_PREVIO VARCHAR2(2000),
  TX_NUMERO_DOCUMENTO_PREVIO VARCHAR2(500),
  FE_DOCUMENTO_PREVIO DATE,
  FE_REGISTRO_DOCUMENTO_PREVIO DATE,
  TX_OTRO_DOCUMENTO_PREVIO VARCHAR2(2000),
  FE_DERIV_DOC_DERIVACION DATE,
  ID_ADMINISTRADO VARCHAR2(500),
  ID_UF VARCHAR2(500),
  RECOM_ACCION VARCHAR2(2000),
  SECTOR_O_SUBSECTOR VARCHAR2(500),
  DIREC VARCHAR2(500),
  COORDINADOR VARCHAR2(1000),
  DIRECTOR VARCHAR2(1000),
  DOC_INICIO_ELA VARCHAR2(2000),
  FECHA_INICIO_ELA DATE,
  PROVEIDO VARCHAR2(1000),
  FECHA_PROV DATE,
  TIPO_INFRACCION VARCHAR2(500),
  DAÑO_RIESGO_ASOCIADO VARCHAR2(500),
  HUMANOS NUMBER,
  AIRE NUMBER,
  FLORA NUMBER,
  FAUNA NUMBER,
  AGUA NUMBER,
  SUELO NUMBER,
  TIPO_SUBSANACION VARCHAR2(500),
  PRESUNTOS_INCUMPL NUMBER,
  TOTAL_HECHOS NUMBER,
  ACTA_TRANSF VARCHAR2(500),
  FECHA_ACTA_TRASNF DATE,
  RPS VARCHAR2(500),
  FECHA_RPS DATE,
  RECOMENDACION_MEDIDAS_ADMIN VARCHAR2(2000),
  RES_ACTA_MEDIDA VARCHAR2(2000),
  FECHA_MEDIDA DATE,
  ESTADO VARCHAR2(500),
  ANALISTA_LEGAL VARCHAR2(1000),
  RESPONSABLE_COMISION VARCHAR2(1000),
  OD VARCHAR2(1000),
  CATEG VARCHAR2(500),
  COMPET VARCHAR2(500),
  TIPO_OD VARCHAR2(500),
  FG_SIN_INFORME NUMBER
,
  FECHA_CARGA DATE
);

COMMENT ON TABLE APP.DW_INF_CONSOL_FORM IS 'Informes consolidados BD+OD (RData 2019–2026). Estructura anclada a esquema vigente 2025/2026; histórico vía EQUIV/NULL. ETL: Hop+H2+Python → full refresh.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FUENTE IS 'Origen del corte: BD (boletin central) u OD (oficinas desconcentradas).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ANIO IS 'Año del corte extraído del nombre del archivo RData.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.MES_CORTE IS 'Mes del corte (ej. AGOSTO, DICIEMBRE) desde el nombre del archivo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ARCHIVO IS 'Basename del archivo .RData de origen.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.OBJETO_R IS 'Nombre del data.frame R cargado desde el RData.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.INFORME IS 'Identificador / número del informe de supervisión.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_INFORME IS 'Fecha del informe.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.EXPEDIENTE IS 'Número de expediente (EQUIV: EXPEDIENTE, TXNUMEXP).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.CUC_INAPS IS 'Código único de caso (CUC) en INAPS.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ADMIN IS 'Administrado / administrado INAPS (EQUIV: ADMIN, ADMINISTRADO_INAPS, TXADMINISTRADO_ADM).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.UF IS 'Unidad fiscalizable (EQUIV: UF, UF_INAPS, TXUNIDAD).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.HECHO_VERIF IS 'Descripción del hecho verificado (texto largo).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPIFICA_HECHO IS 'Tipificación del hecho.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.CLASIF_HECHO IS 'Clasificación del hecho.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RESULT_HECHO IS 'Resultado del hecho.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.MOTIVO_ARCHIV_CONOC IS 'Motivo de archivamiento / conocimiento.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RECOM_INFORME IS 'Recomendación consignada en el informe.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.DOC_CIERRE IS 'Documento de cierre.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.NRO_DOC_CIERRE IS 'Número del documento de cierre.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_DOC_CIERRE IS 'Fecha del documento de cierre.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_DERIV IS 'Fecha de derivación.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FEINICIO IS 'Fecha de inicio de la supervisión / acción.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FEFIN IS 'Fecha de fin de la supervisión / acción.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPOSUP_INAPS IS 'Tipo de supervisión INAPS (EQUIV: TIPOSUP_INAPS, TXTIPSUP).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUPERV_ORIENTATIVA IS 'Indicador / marca de supervisión orientativa.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.MES_META IS 'Mes meta asociado al informe.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPO_INF IS 'Tipo de informe.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TXCOORDINACION IS 'Coordinación (EQUIV: TXCOORDINACION, COORDINACION).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.OBLIG_CUMPL IS 'Cantidad de obligaciones cumplidas.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.OBL_INCUMPLIDA IS 'Cantidad de obligaciones incumplidas.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUBSANA IS 'Marca / texto de subsanación.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUBS_LEVE IS 'Conteo de subsanaciones leves.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUBS_TRAS IS 'Conteo de subsanaciones trascendentales.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUBSANADO IS 'Conteo / flag de hechos subsanados.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.CUMPLIM_ADD IS 'Cumplimiento adicional (conteo).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FILTRO_INF_UNIQ IS 'Flag de filtro para informe único.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPOACCION_INAPS IS 'Tipo de acción INAPS (EQUIV: TIPOACCION_INAPS, TXACCION).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_REAL IS 'Fecha real de la acción / supervisión.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.YEAR_APROB IS 'Año de aprobación.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FEINI_ELAB_INF IS 'Fecha de inicio de elaboración del informe.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TX_DOCUMENTO_PREVIO IS 'Tipo / descripción del documento previo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TX_NUMERO_DOCUMENTO_PREVIO IS 'Número del documento previo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FE_DOCUMENTO_PREVIO IS 'Fecha del documento previo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FE_REGISTRO_DOCUMENTO_PREVIO IS 'Fecha de registro del documento previo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TX_OTRO_DOCUMENTO_PREVIO IS 'Otro documento previo (texto).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FE_DERIV_DOC_DERIVACION IS 'Fecha de derivación del documento de derivación.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ID_ADMINISTRADO IS 'Id del administrado (EQUIV: IDADMIN, IDAMIN, ID_ADMIN, IDADMINISTRADO).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ID_UF IS 'Id de la unidad fiscalizable (EQUIV: IDUF, ID_UF, IDUF_SIG).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RECOM_ACCION IS 'Recomendación de acción / medidas (EQUIV: RECOM_INAPS, RECOM_MA, RECOM_MEDIDAS).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SECTOR_O_SUBSECTOR IS 'Sector (BD) o subsector (OD) coalescido (EQUIV: SECTOR, SUBSECTOR, TXSUBSECTOR_UND).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.DIREC IS '[BD] Dirección / área orgánica.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.COORDINADOR IS '[BD] Coordinador responsable.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.DIRECTOR IS '[BD] Director responsable.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.DOC_INICIO_ELA IS '[BD] Documento de inicio de elaboración.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_INICIO_ELA IS '[BD] Fecha de inicio de elaboración.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.PROVEIDO IS '[BD] Proveído.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_PROV IS '[BD] Fecha del proveído.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPO_INFRACCION IS '[BD] Tipo de infracción.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.DAÑO_RIESGO_ASOCIADO IS '[BD] Daño o riesgo asociado al hecho.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.HUMANOS IS '[BD] Flag/conteo componente humanos.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.AIRE IS '[BD] Flag/conteo componente aire.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FLORA IS '[BD] Flag/conteo componente flora.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FAUNA IS '[BD] Flag/conteo componente fauna.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.AGUA IS '[BD] Flag/conteo componente agua.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.SUELO IS '[BD] Flag/conteo componente suelo.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPO_SUBSANACION IS '[BD] Tipo de subsanación.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.PRESUNTOS_INCUMPL IS '[BD] Presuntos incumplimientos (conteo).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TOTAL_HECHOS IS '[BD] Total de hechos.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ACTA_TRANSF IS '[BD] Acta de transferencia.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_ACTA_TRASNF IS '[BD] Fecha del acta de transferencia.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RPS IS '[BD] RPS / resolución asociada.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_RPS IS '[BD] Fecha del RPS.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RECOMENDACION_MEDIDAS_ADMIN IS '[BD] Recomendación de medidas administrativas (EQUIV nombre con espacios).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RES_ACTA_MEDIDA IS '[BD] Resolución / acta de medida.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_MEDIDA IS '[BD] Fecha de la medida.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ESTADO IS '[BD] Estado del registro en el export vigente.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.ANALISTA_LEGAL IS '[BD] Analista legal asignado.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.RESPONSABLE_COMISION IS '[BD] Responsable de comisión.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.OD IS '[OD] Oficina desconcentrada.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.CATEG IS '[OD] Categoría.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.COMPET IS '[OD] Competencia.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.TIPO_OD IS '[OD] Tipo OD (fuente TIPO; no confundir con TIPO_INF).'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FG_SIN_INFORME IS 'QA ETL (logica/): 1 si INFORME vacío/nulo; 0 en caso contrario.'
COMMENT ON COLUMN APP.DW_INF_CONSOL_FORM.FECHA_CARGA IS 'Instante de carga ETL hacia DW_INF_CONSOL_FORM (Hop pl_form_informes).'
